version: '3.8'
services:
  php-apache-environment:
    container_name: php-server
    hostname: server-bakend
    image: php:apache
    volumes:
      - type: bind
        source: ./backend/src
        target: /var/www/html/
    ports:
      - 80:80